/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CallCenter;
import modelo.Empleado;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import controlador.EmpleadoDAO;

public class frmPrincipal extends javax.swing.JFrame {
    
    LinkedList<Empleado> empObjectList = new LinkedList<>();
    EmpleadoDAO EmpleadoDAO = new EmpleadoDAO();
    CallCenter callCenter = new CallCenter();
    Empleado empleado;
    

    public frmPrincipal() {
        initComponents();
        this.empObjectList = EmpleadoDAO.ListaEmpleado();
        this.listaEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelLiqNomina = new javax.swing.JPanel();
        jPanelBusqueda = new javax.swing.JPanel();
        jLabelTituloLiq = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jPanelDatosEmpleados = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jPanelInfNomina = new javax.swing.JPanel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelValorHorasExtras = new javax.swing.JLabel();
        jCheckBoxAuxTransporte = new javax.swing.JCheckBox();
        jTextFieldSalario = new javax.swing.JTextField();
        jTextFieldValorHorasExtras = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonGenerarNomina = new javax.swing.JButton();
        jPanelTotalNomina = new javax.swing.JPanel();
        jLabelTotalNomina = new javax.swing.JLabel();
        jLabelTotalPrestaciones = new javax.swing.JLabel();
        jTextFieldTotalNomina = new javax.swing.JTextField();
        jTextFieldTotalPrestaciones = new javax.swing.JTextField();
        jPanelCrear = new javax.swing.JPanel();
        jPanelCrearEmpleado = new javax.swing.JPanel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelCNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCNombres = new javax.swing.JTextField();
        jTextFieldCApellidos = new javax.swing.JTextField();
        jLabelCSalario = new javax.swing.JLabel();
        jLabelCvalorHE = new javax.swing.JLabel();
        jTextFieldCSalario = new javax.swing.JTextField();
        jTextFieldCvlrHE = new javax.swing.JTextField();
        jCheckBoxCAT = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanelEditar = new javax.swing.JPanel();
        jPanelEConsulta = new javax.swing.JPanel();
        jLabelEConsultar = new javax.swing.JLabel();
        jTextFieldECodigo = new javax.swing.JTextField();
        jButtonEConsultar = new javax.swing.JButton();
        jPanelEInformacion = new javax.swing.JPanel();
        jLabelENombre = new javax.swing.JLabel();
        jLabelEApellidos = new javax.swing.JLabel();
        jLabelESalario = new javax.swing.JLabel();
        jLabelEvlrHE = new javax.swing.JLabel();
        jTextFieldENombres = new javax.swing.JTextField();
        jTextFieldEApellidos = new javax.swing.JTextField();
        jTextFieldESalarios = new javax.swing.JTextField();
        jTextFieldEvlrHE = new javax.swing.JTextField();
        jCheckBoxEAuxTransp = new javax.swing.JCheckBox();
        jButtonEGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelEConsulta1 = new javax.swing.JPanel();
        jLabelEConsultar1 = new javax.swing.JLabel();
        jTextFieldECodigo1 = new javax.swing.JTextField();
        jButtonEConsultar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonProcesar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNominasMasivas = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleado = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Nomina");

        jPanelBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTituloLiq.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloLiq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloLiq.setText("Consultar Empleado");

        jLabelCodigo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelCodigo.setText("Codigo:");

        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaLayout = new javax.swing.GroupLayout(jPanelBusqueda);
        jPanelBusqueda.setLayout(jPanelBusquedaLayout);
        jPanelBusquedaLayout.setHorizontalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                                .addComponent(jLabelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTituloLiq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBusquedaLayout.setVerticalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloLiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelDatosEmpleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombres:");

        jLabelApellidos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApellidos.setText("Apellidos:");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldApellidos.setEditable(false);
        jTextFieldApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanelInfNomina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSalario.setText("Salario:");

        jLabelValorHorasExtras.setText("Valor HorasExtras:");

        jCheckBoxAuxTransporte.setText("Auxilio Transporte");

        jTextFieldSalario.setEditable(false);
        jTextFieldSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldValorHorasExtras.setEditable(false);
        jTextFieldValorHorasExtras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanelInfNominaLayout = new javax.swing.GroupLayout(jPanelInfNomina);
        jPanelInfNomina.setLayout(jPanelInfNominaLayout);
        jPanelInfNominaLayout.setHorizontalGroup(
            jPanelInfNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfNominaLayout.createSequentialGroup()
                        .addComponent(jLabelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSalario))
                    .addGroup(jPanelInfNominaLayout.createSequentialGroup()
                        .addComponent(jLabelValorHorasExtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorHorasExtras))
                    .addGroup(jPanelInfNominaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jCheckBoxAuxTransporte)
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInfNominaLayout.setVerticalGroup(
            jPanelInfNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorHorasExtras)
                    .addComponent(jTextFieldValorHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jCheckBoxAuxTransporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informacion a Liquidar");

        jButtonGenerarNomina.setText("Generar Nomina");
        jButtonGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNominaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosEmpleadosLayout = new javax.swing.GroupLayout(jPanelDatosEmpleados);
        jPanelDatosEmpleados.setLayout(jPanelDatosEmpleadosLayout);
        jPanelDatosEmpleadosLayout.setHorizontalGroup(
            jPanelDatosEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelApellidos)
                                .addGap(171, 171, 171))
                            .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                                .addGroup(jPanelDatosEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldApellidos)
                                    .addComponent(jTextFieldNombre)
                                    .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                                        .addComponent(jLabelNombre)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanelInfNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelDatosEmpleadosLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jButtonGenerarNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosEmpleadosLayout.setVerticalGroup(
            jPanelDatosEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosEmpleadosLayout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelInfNomina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerarNomina)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanelTotalNomina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTotalNomina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTotalNomina.setText("Total Nomina X Pagar:");

        jLabelTotalPrestaciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTotalPrestaciones.setText("Total Prestaciones Sociales:");

        jTextFieldTotalNomina.setEditable(false);
        jTextFieldTotalNomina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldTotalNomina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalNomina.setText("0");

        jTextFieldTotalPrestaciones.setEditable(false);
        jTextFieldTotalPrestaciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldTotalPrestaciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalPrestaciones.setText("0");

        javax.swing.GroupLayout jPanelTotalNominaLayout = new javax.swing.GroupLayout(jPanelTotalNomina);
        jPanelTotalNomina.setLayout(jPanelTotalNominaLayout);
        jPanelTotalNominaLayout.setHorizontalGroup(
            jPanelTotalNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalNominaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelTotalNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalNomina)
                    .addComponent(jLabelTotalPrestaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTotalNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTotalNomina, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotalPrestaciones))
                .addGap(25, 25, 25))
        );
        jPanelTotalNominaLayout.setVerticalGroup(
            jPanelTotalNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalNominaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelTotalNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalNomina)
                    .addComponent(jTextFieldTotalNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelTotalNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalPrestaciones)
                    .addComponent(jTextFieldTotalPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanelLiqNominaLayout = new javax.swing.GroupLayout(jPanelLiqNomina);
        jPanelLiqNomina.setLayout(jPanelLiqNominaLayout);
        jPanelLiqNominaLayout.setHorizontalGroup(
            jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiqNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatosEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTotalNomina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLiqNominaLayout.setVerticalGroup(
            jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiqNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTotalNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Liq. Nomina", jPanelLiqNomina);
        jPanelLiqNomina.getAccessibleContext().setAccessibleName("LiqNomina");

        jPanelCrearEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelCNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelCNombre.setText("Nombres:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Apellidos:");

        jTextFieldCNombres.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldCApellidos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabelCSalario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelCSalario.setText("Salario:");

        jLabelCvalorHE.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelCvalorHE.setText("Vlr Horas Extras:");

        jTextFieldCSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCSalario.setText("0");
        jTextFieldCSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCSalarioActionPerformed(evt);
            }
        });

        jTextFieldCvlrHE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCvlrHE.setText("0");

        jCheckBoxCAT.setText("Auxilio Transporte");
        jCheckBoxCAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearEmpleadoLayout = new javax.swing.GroupLayout(jPanelCrearEmpleado);
        jPanelCrearEmpleado.setLayout(jPanelCrearEmpleadoLayout);
        jPanelCrearEmpleadoLayout.setHorizontalGroup(
            jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearEmpleadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabelCNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCApellidos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(jCheckBoxCAT)
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCvalorHE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCvlrHE, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldCSalario))))
                .addContainerGap())
            .addGroup(jPanelCrearEmpleadoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCrearEmpleadoLayout.setVerticalGroup(
            jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearEmpleadoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCNombre)
                    .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCSalario)
                        .addComponent(jTextFieldCSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCvalorHE)
                        .addComponent(jTextFieldCvlrHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxCAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCrearLayout = new javax.swing.GroupLayout(jPanelCrear);
        jPanelCrear.setLayout(jPanelCrearLayout);
        jPanelCrearLayout.setHorizontalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCrearEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCrearLayout.setVerticalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Informacion Nomina  Empleado", jPanelCrear);

        jPanelEConsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelEConsultar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelEConsultar.setText("Codigo:");

        jTextFieldECodigo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextFieldECodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonEConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonEConsultar.setText("Consultar");
        jButtonEConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEConsultaLayout = new javax.swing.GroupLayout(jPanelEConsulta);
        jPanelEConsulta.setLayout(jPanelEConsultaLayout);
        jPanelEConsultaLayout.setHorizontalGroup(
            jPanelEConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEConsultaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelEConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldECodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonEConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelEConsultaLayout.setVerticalGroup(
            jPanelEConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEConsultar)
                        .addComponent(jTextFieldECodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEInformacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelENombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelENombre.setText("Nombres:");

        jLabelEApellidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEApellidos.setText("Apellidos:");

        jLabelESalario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelESalario.setText("Salario:");

        jLabelEvlrHE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEvlrHE.setText("Vlr Horas Extras:");

        jTextFieldENombres.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldENombres.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldENombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldENombresActionPerformed(evt);
            }
        });

        jTextFieldEApellidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldEApellidos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldESalarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldESalarios.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldEvlrHE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldEvlrHE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jCheckBoxEAuxTransp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxEAuxTransp.setText("Auxilio Transporte");

        jButtonEGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonEGuardar.setText("Guardar");
        jButtonEGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEInformacionLayout = new javax.swing.GroupLayout(jPanelEInformacion);
        jPanelEInformacion.setLayout(jPanelEInformacionLayout);
        jPanelEInformacionLayout.setHorizontalGroup(
            jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEInformacionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelENombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldENombres))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEInformacionLayout.createSequentialGroup()
                        .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEApellidos)
                            .addComponent(jLabelESalario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEApellidos)
                            .addComponent(jTextFieldESalarios))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelEvlrHE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEvlrHE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxEAuxTransp))
                .addContainerGap())
            .addGroup(jPanelEInformacionLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jButtonEGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEInformacionLayout.setVerticalGroup(
            jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEInformacionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelENombre)
                    .addComponent(jLabelEvlrHE)
                    .addComponent(jTextFieldENombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEvlrHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEApellidos)
                    .addComponent(jTextFieldEApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxEAuxTransp))
                .addGap(54, 54, 54)
                .addGroup(jPanelEInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelESalario)
                    .addComponent(jTextFieldESalarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEGuardar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelEInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelEInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Editar Nomina", jPanelEditar);

        jPanelEConsulta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelEConsultar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelEConsultar1.setText("Codigo:");

        jTextFieldECodigo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextFieldECodigo1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonEConsultar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonEConsultar1.setText("Eliminar");
        jButtonEConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEConsultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEConsulta1Layout = new javax.swing.GroupLayout(jPanelEConsulta1);
        jPanelEConsulta1.setLayout(jPanelEConsulta1Layout);
        jPanelEConsulta1Layout.setHorizontalGroup(
            jPanelEConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEConsulta1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelEConsultar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldECodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonEConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelEConsulta1Layout.setVerticalGroup(
            jPanelEConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEConsulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEConsultar1)
                        .addComponent(jTextFieldECodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEConsultar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEConsulta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Eliminar Nomina", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Diciembre" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Mes:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Año:");

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("2022");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonProcesar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonProcesar.setText("Procesar");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Definitiva");

        jCheckBox2.setText("Prueba");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 159, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(37, 37, 37)
                        .addComponent(jCheckBox2)
                        .addGap(80, 80, 80))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jListNominasMasivas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneMenu.addTab("Liq. Masiva Nomina", jPanel2);

        jListEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Empleado 1", "Empleado 2", "Empleado 3", "Empleado 4", "Empleado 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEmpleado);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lista de Empleados");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Empleados", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPaneMenu)
                .addContainerGap())
        );

        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("Liq. Nomina");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed
        // TODO add your handling code here:

        LinkedList<Empleado> empleados = EmpleadoDAO.ListaEmpleado();
        HashMap<Integer, ArrayList> listaNomina = new HashMap<Integer, ArrayList>();

        listaNomina = callCenter.procesoMasivoNomina(empleados);

        if(listaNomina != null){
            //listaNominasPrestaciones(procesos);
            listaNominasPrestaciones(listaNomina);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Error en el proceso intente nuevamente");
        }
    }//GEN-LAST:event_jButtonProcesarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonEConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEConsultar1ActionPerformed
        // TODO add your handling code here:

        try {

            empleado = EmpleadoDAO.consultaEmpleadoId(jTextFieldECodigo1.getText());

            if(empleado==null){

                JOptionPane.showMessageDialog(rootPane, "No existe el empleado");

            }else{

                int conf = JOptionPane.showConfirmDialog(rootPane, "Realmente quiere eliminar este empleado? \n" + empleado.getNombre() + " " + empleado.getApellidos());

                if(conf == JOptionPane.YES_OPTION){
                    EmpleadoDAO.eliminarEmpleado(jTextFieldECodigo1.getText());
                    JOptionPane.showMessageDialog(rootPane, "Empleado eliminado exitosamente: \n"+ empleado.getNombre() + " " + empleado.getApellidos());
                    jTextFieldECodigo1.setText("");
                    actVistaEmpleado();
                }else{
                    if(conf == JOptionPane.NO_OPTION){
                        JOptionPane.showMessageDialog(rootPane, "Empleado no eliminado: \n"+ empleado.getNombre() + " " + empleado.getApellidos());
                        jTextFieldECodigo1.setText("");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: "+ e.getMessage());
        }
    }//GEN-LAST:event_jButtonEConsultar1ActionPerformed

    private void jButtonEGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEGuardarActionPerformed
        // TODO add your handling code here:
        try {

            if(jTextFieldENombres.getText().equals("") || jTextFieldEApellidos.getText().equals("") || (Integer.valueOf(jTextFieldESalarios.getText()) <= 0) || (Integer.valueOf(jTextFieldEvlrHE.getText()) < 0) ){
                JOptionPane.showMessageDialog(rootPane, "Valor del nombre, apellido y salario, son obligatorios");
            }else{
                String auxTransString;
                boolean auxTransBo = jCheckBoxEAuxTransp.isSelected();

                if(auxTransBo){
                    auxTransString = "true";
                }else{
                    auxTransString = "false";
                }

                empleado = EmpleadoDAO.actualizarEmpleado(jTextFieldENombres.getText(),jTextFieldEApellidos.getText(),Integer.valueOf(jTextFieldEvlrHE.getText()),auxTransString,Integer.valueOf(jTextFieldESalarios.getText()),jTextFieldECodigo.getText());

                if(empleado==null){
                    JOptionPane.showMessageDialog(rootPane, "Empleado No Guardado");
                    jTextFieldECodigo.setText("");
                    jTextFieldENombres.setText("");
                    jTextFieldEvlrHE.setText("");
                    jTextFieldEApellidos.setText("");
                    jTextFieldESalarios.setText("");
                    jCheckBoxEAuxTransp.setSelected(false);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Empleado Guardado Exitosamente");
                    jTextFieldECodigo.setText("");
                    jTextFieldENombres.setText("");
                    jTextFieldEvlrHE.setText("");
                    jTextFieldEApellidos.setText("");
                    jTextFieldESalarios.setText("");
                    jCheckBoxEAuxTransp.setSelected(false);
                    actVistaEmpleado();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: Salario y Hora Extra deben ser de tipo numerico \n"+ e.getMessage());
            jTextFieldECodigo.setText("");
            jTextFieldENombres.setText("");
            jTextFieldEvlrHE.setText("");
            jTextFieldEApellidos.setText("");
            jTextFieldESalarios.setText("");
            jCheckBoxEAuxTransp.setSelected(false);
        }
    }//GEN-LAST:event_jButtonEGuardarActionPerformed

    private void jTextFieldENombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldENombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldENombresActionPerformed

    private void jButtonEConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEConsultarActionPerformed
        // TODO add your handling code here:
        try {

            empleado = EmpleadoDAO.consultaEmpleadoId(jTextFieldECodigo.getText());

            if(empleado==null){
                JOptionPane.showMessageDialog(rootPane, "No existe el empleado");
                jTextFieldECodigo.setText("");
                jTextFieldENombres.setText("");
                jTextFieldEApellidos.setText("");
                jTextFieldESalarios.setText("");
                jTextFieldEvlrHE.setText("");
                jCheckBoxEAuxTransp.setSelected(false);
            }else{

                jTextFieldENombres.setText(empleado.getNombre());
                jTextFieldEApellidos.setText(empleado.getApellidos());
                jTextFieldESalarios.setText(String.valueOf(empleado.getSalario()));
                jTextFieldEvlrHE.setText(String.valueOf(empleado.getHorasExtra()));
                jCheckBoxEAuxTransp.setSelected(empleado.isAuxilioTransporte());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: "+ e.getMessage());
        }
    }//GEN-LAST:event_jButtonEConsultarActionPerformed

    private void jCheckBoxCATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCATActionPerformed

    private void jTextFieldCSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCSalarioActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:

        try {

            if(jTextFieldCNombres.getText().equals("") || jTextFieldCApellidos.getText().equals("") || (Integer.valueOf(jTextFieldCSalario.getText()) <= 0) || (Integer.valueOf(jTextFieldCvlrHE.getText()) < 0) ){
                JOptionPane.showMessageDialog(rootPane, "Valor del nombre, apellido y salario, son obligatorios");
            }else{
                String auxTransString;
                boolean auxTransBo = jCheckBoxCAT.isSelected();

                if(auxTransBo){
                    auxTransString = "true";
                }else{
                    auxTransString = "false";
                }

                EmpleadoDAO.crearEmpleado(jTextFieldCNombres.getText(), jTextFieldCApellidos.getText(), Integer.valueOf(jTextFieldCvlrHE.getText()), auxTransString, Integer.valueOf(jTextFieldCSalario.getText()));

                JOptionPane.showMessageDialog(rootPane, "Empleado Guardado Exitosamente");
                jTextFieldCNombres.setText("");
                jTextFieldCApellidos.setText("");
                jTextFieldCSalario.setText("0");
                jTextFieldCvlrHE.setText("0");
                jCheckBoxCAT.setSelected(false);
                actVistaEmpleado();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: Salario y Hora Extra deben ser de tipo numerico \n"+ e.getMessage());
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNominaActionPerformed
        // TODO add your handling code here:
        actVistaEmpleado();

        ArrayList<Double> nominas = new ArrayList<>();
        ArrayList<Double> prestaciones = new ArrayList<>();
        ArrayList<Empleado> listEmpleado = new ArrayList<>();

        empleado = EmpleadoDAO.consultaEmpleadoId(jTextFieldCodigo.getText());
        if(empleado != null){
            listEmpleado.add(empleado);

            nominas = callCenter.liquidarNominaEmp(listEmpleado);
            jTextFieldTotalNomina.setText(String.valueOf(Math.round(nominas.get(0))));

            prestaciones = callCenter.liquidarPrestacionesEmp(listEmpleado);
            jTextFieldTotalPrestaciones.setText(String.valueOf(Math.round(prestaciones.get(0))));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Error: en el proceso intente de nuevo");
        }
    }//GEN-LAST:event_jButtonGenerarNominaActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:

        try {

            EmpleadoDAO modelConsultar = new EmpleadoDAO();
            Empleado empl = modelConsultar.consultaEmpleadoId(jTextFieldCodigo.getText());

            if(empl==null){
                JOptionPane.showMessageDialog(rootPane, "No existe el empleado");
                jTextFieldCodigo.setText("");
                jTextFieldNombre.setText("");
                jTextFieldApellidos.setText("");
                jTextFieldSalario.setText("");
                jTextFieldValorHorasExtras.setText("");
                jCheckBoxAuxTransporte.setSelected(false);

                jTextFieldTotalNomina.setText("");
                jTextFieldTotalPrestaciones.setText("");

            }else{

                jTextFieldTotalNomina.setText("");
                jTextFieldTotalPrestaciones.setText("");

                jTextFieldNombre.setText(empl.getNombre());
                jTextFieldApellidos.setText(empl.getApellidos());
                jTextFieldSalario.setText(String.valueOf(empl.getSalario()));
                jTextFieldValorHorasExtras.setText(String.valueOf(empl.getHorasExtra()));
                jCheckBoxAuxTransporte.setSelected(empl.isAuxilioTransporte());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: "+ e.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void listaNominasPrestaciones(HashMap<Integer, ArrayList> listaNomina){

        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (ArrayList i : listaNomina.values()) {
            
            String data = "Id: " + i.get(0) + " NOMBRE: " +  i.get(1) + " NOMINA: " +  i.get(2) + " PRESTACIONES: "+ i.get(3);
                                  
            model.add(index, data);
            index++;  
        }
        
        jListNominasMasivas.setModel(model);
        
    }
    
    private void listaEmpleado(){
        
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (Empleado empleado : empObjectList) {
            String data =  (index+1) + " ) Id: " + empleado.getId() + " - "  +  empleado.getNombre() + " - " + empleado.getApellidos() + 
                                       "\n Horas Extras: " + empleado.getHorasExtra() + 
                                       "\n Valor Salario: " + empleado.getSalario() + 
                                       "\n Auxilio Transporte \n" + empleado.isAuxilioTransporte();
            System.out.println();
            model.add(index, data);
            index++;
        }
        jListEmpleado.setModel(model);
    }
    
    private void actVistaEmpleado(){
        this.empObjectList = EmpleadoDAO.ListaEmpleado();
        this.listaEmpleado();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonEConsultar;
    private javax.swing.JButton jButtonEConsultar1;
    private javax.swing.JButton jButtonEGuardar;
    private javax.swing.JButton jButtonGenerarNomina;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBoxAuxTransporte;
    private javax.swing.JCheckBox jCheckBoxCAT;
    private javax.swing.JCheckBox jCheckBoxEAuxTransp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCNombre;
    private javax.swing.JLabel jLabelCSalario;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCvalorHE;
    private javax.swing.JLabel jLabelEApellidos;
    private javax.swing.JLabel jLabelEConsultar;
    private javax.swing.JLabel jLabelEConsultar1;
    private javax.swing.JLabel jLabelENombre;
    private javax.swing.JLabel jLabelESalario;
    private javax.swing.JLabel jLabelEvlrHE;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTituloLiq;
    private javax.swing.JLabel jLabelTotalNomina;
    private javax.swing.JLabel jLabelTotalPrestaciones;
    private javax.swing.JLabel jLabelValorHorasExtras;
    private javax.swing.JList<String> jListEmpleado;
    private javax.swing.JList<String> jListNominasMasivas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelCrear;
    private javax.swing.JPanel jPanelCrearEmpleado;
    private javax.swing.JPanel jPanelDatosEmpleados;
    private javax.swing.JPanel jPanelEConsulta;
    private javax.swing.JPanel jPanelEConsulta1;
    private javax.swing.JPanel jPanelEInformacion;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelInfNomina;
    private javax.swing.JPanel jPanelLiqNomina;
    private javax.swing.JPanel jPanelTotalNomina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCApellidos;
    private javax.swing.JTextField jTextFieldCNombres;
    private javax.swing.JTextField jTextFieldCSalario;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCvlrHE;
    private javax.swing.JTextField jTextFieldEApellidos;
    private javax.swing.JTextField jTextFieldECodigo;
    private javax.swing.JTextField jTextFieldECodigo1;
    private javax.swing.JTextField jTextFieldENombres;
    private javax.swing.JTextField jTextFieldESalarios;
    private javax.swing.JTextField jTextFieldEvlrHE;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldTotalNomina;
    private javax.swing.JTextField jTextFieldTotalPrestaciones;
    private javax.swing.JTextField jTextFieldValorHorasExtras;
    // End of variables declaration//GEN-END:variables
}
